num=2
print(num,'의 제곱근 =',num**0.5)
num=num+1
print(num,'의 제곱근 =',num**0.5)
num=num+1
print(num,'의 제곱근 =',num**0.5)
num=num+1
print(num,'의 제곱근 =',num**0.5)
num=num+1
print(num,'의 제곱근 =',num**0.5)
num=num+1
print(num,'의 제곱근 =',num**0.5)
num=num+1
print(num,'의 제곱근 =',num**0.5)
num=num+1
print(num,'의 제곱근 =',num**0.5)
num=num+1
print(num,'의 제곱근 =',num**0.5)
num=num+1
